import { useState } from 'react';
import CopyButton from '../shared/CopyButton';

interface FormData {
  websiteName: string;
  websiteUrl: string;
  email: string;
  usesAnalytics: boolean;
  usesAds: boolean;
  usesSession: boolean;
  usesPreferences: boolean;
  usesThirdParty: boolean;
}

function generatePolicy(data: FormData): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const cookies: string[] = [];
  if (data.usesSession) cookies.push(`- **Session Cookies**: Essential cookies that keep you logged in and maintain your session. These expire when you close your browser.`);
  if (data.usesPreferences) cookies.push(`- **Preference Cookies**: Store your settings and preferences (language, theme, layout). These persist between visits.`);
  if (data.usesAnalytics) cookies.push(`- **Analytics Cookies**: Help us understand how visitors interact with our website by collecting anonymous usage data. We use services like Google Analytics for this purpose.`);
  if (data.usesAds) cookies.push(`- **Advertising Cookies**: Used by our ad partners to deliver relevant advertisements and track ad performance. These may be set by third-party advertising networks.`);
  if (data.usesThirdParty) cookies.push(`- **Third-Party Cookies**: Set by external services embedded on our pages (social media widgets, embedded videos, payment processors).`);

  return `# Cookie Policy

**Last updated:** ${date}

## What Are Cookies?

Cookies are small text files stored on your device when you visit a website. They help websites remember your preferences, understand how you use the site, and improve your experience. Some cookies are essential for the website to function, while others are optional.

## How ${data.websiteName || '[Website Name]'} Uses Cookies

We use the following types of cookies on ${data.websiteUrl || '[Website URL]'}:

${cookies.join('\n\n')}

## Managing Cookies

You can control and manage cookies through your browser settings. Most browsers allow you to:

- View and delete existing cookies
- Block all cookies or only third-party cookies
- Set preferences for specific websites
- Get notifications when a cookie is set

Please note that disabling essential cookies may affect the functionality of our website.

### Browser-Specific Instructions

- **Chrome**: Settings > Privacy and Security > Cookies
- **Firefox**: Settings > Privacy & Security > Cookies
- **Safari**: Preferences > Privacy > Manage Website Data
- **Edge**: Settings > Cookies and Site Permissions

## Cookie Consent

When you first visit our website, we display a cookie banner asking for your consent to set non-essential cookies. You can change your preferences at any time by clearing your cookies and revisiting the site.

## Changes to This Policy

We may update this Cookie Policy from time to time to reflect changes in our practices or for legal, operational, or regulatory reasons. The updated date at the top indicates the latest revision.

## Contact Us

If you have questions about our use of cookies, contact us at **${data.email || '[email address]'}**.

---

*Generated by FreeToolStack's Cookie Policy Generator. This is a template for informational purposes only and does not constitute legal advice. Consult a licensed attorney before publishing.*`;
}

export default function CookiePolicyGenerator() {
  const [form, setForm] = useState<FormData>({
    websiteName: '', websiteUrl: '', email: '',
    usesAnalytics: true, usesAds: false, usesSession: true, usesPreferences: true, usesThirdParty: false,
  });
  const [output, setOutput] = useState('');

  const update = (key: keyof FormData, value: string | boolean) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  return (
    <div className="space-y-6">
      {!output ? (
        <div className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Website Name</label><input type="text" value={form.websiteName} onChange={(e) => update('websiteName', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="My Website" /></div>
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Website URL</label><input type="url" value={form.websiteUrl} onChange={(e) => update('websiteUrl', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="https://example.com" /></div>
            <div className="sm:col-span-2"><label className="mb-1 block text-sm font-medium text-surface-700">Contact Email</label><input type="email" value={form.email} onChange={(e) => update('email', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="privacy@example.com" /></div>
          </div>
          <div className="space-y-2">
            <p className="text-sm font-medium text-surface-700">Cookie types used:</p>
            {[
              { key: 'usesSession', label: 'Session / essential cookies' },
              { key: 'usesPreferences', label: 'Preference cookies' },
              { key: 'usesAnalytics', label: 'Analytics cookies (e.g., Google Analytics)' },
              { key: 'usesAds', label: 'Advertising cookies' },
              { key: 'usesThirdParty', label: 'Third-party cookies (social widgets, embeds)' },
            ].map(({ key, label }) => (
              <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={form[key as keyof FormData] as boolean} onChange={(e) => update(key as keyof FormData, e.target.checked)} className="rounded border-surface-300" /><span className="text-sm text-surface-700">{label}</span></label>
            ))}
          </div>
          <button onClick={() => setOutput(generatePolicy(form))} className="rounded-lg bg-primary-600 px-6 py-2 text-sm font-medium text-white hover:bg-primary-700">Generate Cookie Policy</button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium text-surface-900">Your Cookie Policy</h3>
            <div className="flex gap-2"><CopyButton text={output} label="Copy" /><button onClick={() => setOutput('')} className="rounded-lg border border-surface-200 px-3 py-1.5 text-sm text-surface-700 hover:bg-surface-50">Start Over</button></div>
          </div>
          <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><strong>Disclaimer:</strong> Template only. Not legal advice. Consult a licensed attorney.</div>
          <pre className="max-h-96 overflow-auto rounded-lg border border-surface-200 bg-surface-50 p-4 text-sm whitespace-pre-wrap">{output}</pre>
        </div>
      )}
    </div>
  );
}
