import { useState } from 'react';
import CopyButton from '../shared/CopyButton';

interface FormData {
  companyName: string;
  websiteUrl: string;
  email: string;
  country: string;
  hasUserAccounts: boolean;
  hasPayments: boolean;
  hasUserContent: boolean;
  hasApi: boolean;
}

function generateTerms(data: FormData): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `# Terms of Service

**Last updated:** ${date}

## Acceptance of Terms

By accessing or using ${data.websiteUrl || '[Website URL]'} ("the Service"), operated by ${data.companyName || '[Company Name]'} ("we", "us", or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.

## Description of Service

The Service provides online tools and utilities accessible through our website. We reserve the right to modify, suspend, or discontinue any part of the Service at any time without prior notice.

## Eligibility

You must be at least 13 years of age to use the Service. By using the Service, you represent and warrant that you meet this requirement.

${data.hasUserAccounts ? `## User Accounts

When you create an account, you are responsible for maintaining the confidentiality of your credentials and for all activities under your account. You agree to notify us immediately of any unauthorized use. We reserve the right to terminate accounts that violate these terms.` : ''}

${data.hasPayments ? `## Payments and Subscriptions

Paid features are billed in advance on a recurring basis. You may cancel at any time, but refunds are not provided for partial billing periods. We reserve the right to change pricing with 30 days' notice. All prices are in USD unless otherwise stated.` : ''}

${data.hasUserContent ? `## User-Generated Content

You retain ownership of content you create using our tools. By using the Service, you grant us no rights to your content. Output generated by our tools (formatted text, generated documents, converted files) belongs to you.` : ''}

## Intellectual Property

The Service, including its design, code, and content (excluding user-generated content), is our intellectual property. You may not copy, modify, or distribute our Service without written permission.

## Limitation of Liability

THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR ANY DAMAGES ARISING FROM YOUR USE OF THE SERVICE. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.

## Indemnification

You agree to indemnify and hold harmless ${data.companyName || '[Company Name]'} from any claims, damages, or expenses arising from your use of the Service or violation of these terms.

## Governing Law

These terms are governed by the laws of ${data.country === 'US' ? 'the State of Delaware, United States' : 'the jurisdiction in which the Company is registered'}.

## Termination

We may terminate or suspend your access to the Service immediately, without prior notice, for any breach of these terms.

## Changes to Terms

We reserve the right to modify these terms at any time. We will notify users of material changes by posting the updated terms on our website. Continued use of the Service after changes constitutes acceptance.

## Contact

For questions about these terms, contact us at **${data.email || '[email address]'}**.

---

*This document was generated using UtilityDocker's Terms of Service Generator. It is provided as a template for informational purposes only and does not constitute legal advice. No attorney-client relationship is created. Consult a licensed attorney before publishing.*`;
}

export default function TermsOfServiceGenerator() {
  const [form, setForm] = useState<FormData>({
    companyName: '', websiteUrl: '', email: '', country: 'US',
    hasUserAccounts: false, hasPayments: false, hasUserContent: true, hasApi: false,
  });
  const [output, setOutput] = useState('');

  const update = (key: keyof FormData, value: string | boolean) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  return (
    <div className="space-y-6">
      {!output ? (
        <div className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Company Name</label><input type="text" value={form.companyName} onChange={(e) => update('companyName', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="Acme Inc." /></div>
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Website URL</label><input type="url" value={form.websiteUrl} onChange={(e) => update('websiteUrl', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="https://example.com" /></div>
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Contact Email</label><input type="email" value={form.email} onChange={(e) => update('email', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" placeholder="legal@example.com" /></div>
            <div><label className="mb-1 block text-sm font-medium text-surface-700">Jurisdiction</label><select value={form.country} onChange={(e) => update('country', e.target.value)} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm"><option value="US">United States</option><option value="EU">European Union</option><option value="UK">United Kingdom</option></select></div>
          </div>
          <div className="space-y-2">
            <p className="text-sm font-medium text-surface-700">Service features:</p>
            {[
              { key: 'hasUserAccounts', label: 'User accounts / registration' },
              { key: 'hasPayments', label: 'Paid subscriptions or purchases' },
              { key: 'hasUserContent', label: 'Users create or upload content' },
              { key: 'hasApi', label: 'API access' },
            ].map(({ key, label }) => (
              <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={form[key as keyof FormData] as boolean} onChange={(e) => update(key as keyof FormData, e.target.checked)} className="rounded border-surface-300" /><span className="text-sm text-surface-700">{label}</span></label>
            ))}
          </div>
          <button onClick={() => setOutput(generateTerms(form))} className="rounded-lg bg-primary-600 px-6 py-2 text-sm font-medium text-white hover:bg-primary-700">Generate Terms of Service</button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium text-surface-900">Your Terms of Service</h3>
            <div className="flex gap-2">
              <CopyButton text={output} label="Copy Markdown" />
              <button onClick={() => setOutput('')} className="rounded-lg border border-surface-200 px-3 py-1.5 text-sm text-surface-700 hover:bg-surface-50">Start Over</button>
            </div>
          </div>
          <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            <strong>Disclaimer:</strong> This is a template for informational purposes only. It does not constitute legal advice. Consult a licensed attorney before publishing.
          </div>
          <pre className="max-h-96 overflow-auto rounded-lg border border-surface-200 bg-surface-50 p-4 text-sm whitespace-pre-wrap">{output}</pre>
        </div>
      )}
    </div>
  );
}
